### ISSUE TITLE
Node and Mesh mismatch

### ISSUE THREAD

**Issue by TheNablaOperator** [gimli-org/gimli#369]
### Problem description

If I create a 3D world model (not the closed tank example) and I use createNode for mesh refinement at the electrodes, I get a electrode-mesh mismatch...
How do I properly match the mesh and electrodes including mesh refinement?
According to the tank example it seems to be the same code for 2D and 3D...
Thank you!

### Your environment

**Operating system**: Win10
**Python version**: 3.8.12
**pyGIMLi version**: 1.2.4
**Way of installation**: conda

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli.meshtools as mt
import numpy as np
import pygimli as pg
from pygimli.physics import ert

print(pg.__version__)

world = mt.createWorld(start=[-100, -100, -50],
                       end=[100, 100, 0],
                       worldMarker=True)

block = mt.createCube(size=[30,15,6], pos=[51,7.5,-6], marker=3, boundaryMarker=10)
quad = mt.createCube(size=[69,15,12], pos=[34.5,7.5,-6], marker=2, boundaryMarker=10)

#Merge object
geo = world + quad + block 

#Resistivity Map
rhomap = [[1, 100],
          [2, 100],
          [3, 1000]]

geo.exportVTK("geo")
pg.show(geo)

scheme = ert.createData(elecs=np.linspace(start=0, stop=69, num=24),
                        schemeName='wa')
print(scheme)

# Create Nodes (as in 2D ERT example)
for s in scheme.sensors():
    geo.createNode(s, marker=-99)
    geo.createNode(s - [0, 0, 0.1])

# Create Mesh
mesh = mt.createMesh(geo) 
mesh.exportVTK("mesh.vtk")
pg.show(mesh, geo, notebook=True)

# Make ERT
het = ert.simulate(mesh, 
                   res=rhomap, 
                   scheme=scheme, 
                   #sr=False,
                   #calcOnly=True, 
                   verbose=True,
                   #noiseLevel=1,
                   #noiseAbs=1e-6, seed=1337
                  )

pg.show(het, cMin=100, cMax=300)
```

### Expected behavior

Fine Mesh around electrodes

### Actual behavior

Mismatch of electrodes and mesh. Without creating the nodes, the mesh looks good, but is not fine near the electrodes... Without the nodes the ERT simulation works properly...

```
RuntimeError: There is a requested electrode that does not match the given mesh.
```

**Comment by carsten-forty2** [comment]
Thanks for reporting.

There is a Tetgen error caused by a bad PLC.
```
PLC Error:  A vertex lies in a segment in facet #-1.
  Vertex:  [25] (3,0,0).
  Segment: [15, 13]
```

The problem happens because the rudimentary `pg.meshtools` can't yet handle nodes that intersects with other edges in the geometry .. in your case the electrode with marker = -99. 

If you change your geometry a little, the problem should be solved. On the other hand, you don't need these explicit nodes for injection electrodes since they are only necessary if you want a simulation without a scheme file. The forward operator will find take the right spot for current injection from the sensor positions in the scheme file. 

When you avoid the nodes with marker == -9 and keep the refinement nodes below the surface, the mesh is local refined and the calculation will work.

**Comment by TheNablaOperator** [comment]
@carsten-forty2 thank you for your comment.
The tetgen error sounds familiar to me, I got it at a previous stage in this project...
If I change the geometry, e.g. starting `quad` at `start=[-0.5,-0.5,0]` it still won't work. What do you mean by changing the geometry a "little"?

According to the refinement: Yes, indeed. Avoiding the nodes and doing only the refinement works. 
I still struggle with the results, since it is still not that what I would expect. However, with the refinement the result looks better, but I am not sure if it is ok.
